### PR TITLE
 snr using convolution

### PR DESCRIPTION
**Pull request by kalenkovich**
I refactored the snr calculation.

The new version uses convolution instead of a loop. It still implicitly iterates over all the other dimensions inside `np.apply_along_axis` but the resulting code is more concise. Plus it works with any possible number of dimensions without special treatment.

### CODE REVIEW

**Comment by dominikwelke** [comment]
i'm not experienced in resolving conflicts.. did you do this already?

**Comment by kalenkovich** [comment]
> i'm not experienced in resolving conflicts.. did you do this already?

Sure, I'll rebase onto the current ssvep-tutorial-master and push again.

**Comment by dominikwelke** [comment]
lgtm, sorry for the late review :)

**Comment by dominikwelke** [comment]
to make it more flexible we *could* include an optional parameter to indicate the dimension of time domain (with default e.g. `axis=-1`). but maybe this would be too much..

**Comment by kalenkovich** [comment]
> to make it more flexible we _could_ include an optional parameter to indicate the dimension of time domain (with default e.g. `axis=-1`). but maybe this would be too much..

That is a good idea for the eventual module/package but for the tutorial I'd keep it as is. I would even go as far as removing the function altogether since we are using it only once anyway. If you agree, I could remove the function and just calculate SNR directly in this PR. What do you think?

**Comment by dominikwelke** [comment]
i would probablys leave it as a function. 
sure, it dosnt make much sense in a notebook style tutorial, but i think it can help keeping the code tidy for visitors. there are a few other mne tutorials with functions

i dont care too much though. if you feel strongly, go ahead and remove it :)

**Comment by kalenkovich** [comment]
> i would probablys leave it as a function.
> sure, it dosnt make much sense in a notebook style tutorial, but i think it can help keeping the code tidy for visitors. there are a few other mne tutorials with functions
> 
> i dont care too much though. if you feel strongly, go ahead and remove it :)

Nah, not really. Let's merge then?

**Pull request merged**
